import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AI } from "./action";
const inter = Inter({ subsets: ["latin"] });
import { Provider as JotaiPro, createStore } from "jotai";
import { DevTools } from "jotai-devtools";

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};
const customStore = createStore();

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en">
   <body className={inter.className}>
    {" "}
    <JotaiPro>
     <AI>
      <ThemeProvider
       attribute="class"
       defaultTheme="dark"
       enableSystem
       disableTransitionOnChange
      >
       {children}
      </ThemeProvider>
     </AI>
    </JotaiPro>
   </body>
  </html>
 );
}
